# Generated by Django 3.1.6 on 2023-04-01 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0002_auto_20230328_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='postexpsurveymodel3d',
            name='q5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postexpsurveymodel3d',
            name='q6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postexpsurveymodel3d',
            name='q7',
            field=models.TextField(blank=True, null=True),
        ),
    ]
